format = """
$username\
$hostname\
$directory\
$git_branch\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[λ](purple)"
error_symbol = "[λ](red)"
vimcmd_symbol = "[λ](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
